services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  sysbiz:
    build:
      context: ./sysbiz
      dockerfile: Dockerfile
    container_name: sysbiz_app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - DATABASE_HOST=postgres
    volumes:
      - ./sysbiz:/sysbiz
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: